### ISSUE TITLE
Unable to get anything from sdb(e)

### ISSUE THREAD

**Issue by pandasquee** [aspace-sim/aspace#11]
Ive spent hours and hours trying to figure out how to get aspace going. I followed the instructions to a t found on the wiki and everything seemed to compile ok. But when I do sdb(e) as #1 is just get back sdb(e), no function not found error or anything. Is anyone still around that can help?

**Comment by DieterKoblenz** [comment]
I've managed to get it working in 2015. 

What system are you using to compile? If sdb(e) isn't working, something with the compliling went wrong. Are you using the latest version of pennmush (that could cause issues...) ?

**Comment by mloftis** [comment]
Passes the "smoke test" with PennMush 1.8.8p0

`th version()
PennMUSH version 1.8.8 patchlevel 0 [04/20/2020]
th sdb(e)
1`

My guess is you missed steps.  sdb etc all get added to the function tables via initSpace in space_main.c, which must be added to local_start() in local.dst.

**Comment by pandasquee** [comment]
You;re right I did miss adding the (void) initSpace(); /**< ASpace Related */ to local.dist. I added it, saved, restarted the mush and sdb(e) stuff gives me nothing. I am using the latest version of penn, not sure how to use an earlier version.

**Comment by ray73864** [comment]
I should really finish my plugin system for Penn :)

I have a working version of it, which negates the need to make so many edits to Penn itself when adding in Aspace.

What happens when you type ```@function sdb```?

It should return back the function information, if it doesn't, then something went wrong during the compile, or you forgot to update ```src/Makefile.in```.

**Comment by pandasquee** [comment]
Hi Ray. I've compiled this thing a million times, I went back and looked at
everything and it /seems/ correct. When I get @function sdb I get No Such
Function. Even if its an issue with the version of penn, i assume the
@function would still work. Can anyone come to my server and help me, or
throw me an already compiled version i can drop?

Thanks so much for reading and responding!

**Comment by mloftis** [comment]
> You;re right I did miss adding the (void) initSpace(); /**< ASpace Related */ to local.dist. I added it, saved, restarted the mush and sdb(e) stuff gives me nothing. I am using the latest version of penn, not sure how to use an earlier version.

local.dst is compiled in from the source. You have to update you rebuild anytime you change that, not just restart. Is your build even succeeding? A broken build won't clobber the existing arc/netmud executable.

**Comment by mloftis** [comment]
Autocorrect using the app... it's src/netmud. And obv src/local.dst

**Comment by mike347** [comment]
Sounds like you added the required changes to local.dst AFTER local.c was
generated on your first compile.

Delete local.c and let make regenerate it from the .dst and you should be
good to go.

**Comment by DieterKoblenz** [comment]
I've done a clean install on CentOS 7 (VM) with the most recent checkout from Git on PennMUSH and ASpace. It works (at least sdb returns 1). So what Mike says, try again with deleting those files.

**Comment by mloftis** [comment]
Yeah I did too (well not clean VM just on my usual Dev VM machine)...literally been a probably more than 10y since I did this.  Back then I was a Wiz and the HC guy for Paradox ATS.  I was working alone in a vacuum (in a lot of ways LOL) back then.  I assumed local.c was automatically refreshed from local.dst, and looking at the Makefile/Makefile.in's that is not the case.  You do have to rm it or cp local.dst to local.c, It only spits out a NOTE/warning during compile if local.dst is updated (which...just seems a little silly to me...)

Maybe for later PennMUSH a note needs to be added to the Wiki page there to either edit local.c instead or check for differences and rm local.c if appropriate.

**Comment by pandasquee** [comment]
Hi Mike! Thanks that totally worked! One last question, how do I load the outdb that you included in the package?

**Comment by mike347** [comment]
You should be able to just rename it and replace the outdb in
pennmush/game/data

**Comment by pandasquee** [comment]
Thanks everyone for your help! My server is now up and running. My intention is to open an Aspace Dev server where people can play around with aspace in a in a sandbox without having to install their own. My server is at 143.110.150.253. Obvs it just opened so give it a little time but everyone is welcome at 143.110.150.253 port 4201.
