### ISSUE TITLE
SDB(e) showing up as not valid

### ISSUE THREAD

**Issue by g33kcub** [aspace-sim/aspace#4]
Can you provide me with a copy of the local.dst with the correct settings in. Everything makes, but when I go to use the command th [sdb(e)] I get that is an invalid function

**Comment by ray73864** [comment]
The local.dst changes should be viewable on the wiki, there isn't much to it, just setting up the space iteration stuff and ensuring that space gets saved everytime the mush saves, etc...

What do you see if you type '@function sdb'? it should come back with the details of the function, if it doesn't then it sounds like space_function.c hasn't been compiled in properly, or, most likely, space hasn't even been compiled in at all.

Make sure you made changes to src/Makefile.in, and then reconfigure pennmush to generate the new src/Makefile itself.

**Comment by g33kcub** [comment]
I've tried even getting the system running. I can run it on one of the packaged versions, but those are out of date and don't support the code we're using. Is there a tested and working version of Aspace with the newest build of pennmush.

Also, more documentation on how to actually use aspace would be nice. Most of the links are outdated and your doc makes assumptions you've used it before. Please let me know. Thanks.

**Comment by g33kcub** [comment]
Also I see no file named Space_Function.c in any package.

**Comment by ray73864** [comment]
oh wow, it's completely missing from the repo yet again :(

I was sure I added it last time, anyway, I shall put the file back into it and then that should fix all your issues.

**Comment by ray73864** [comment]
Errr, my bad, it isn't space_function.c, that's something I dreamt up a long long time ago for a different game, no, it's space_main.c that you should have, that is what creates the sdb() function.

The last build I tested aspace on was I believe 1.8.5p5 or p6 and it was working perfectly with that version of Penn.

The Wiki should have everything in terms of getting the hardcode all set up and getting the softcode consoles all set up, always happy to take on pull-requests that improve them, as for how to actually use aspace (creating specifications, etc...) i've never ventured into that territory, the big game I was a wizard on, my job was to keep the hardcode itself functioning with each new release of Pennmush, so the wiki won't really have much on how to do any of that stuff (except for some older information out on the net).

**Comment by g33kcub** [comment]
Ok, so my question is that I get no compile errors. It compiles the various space_*.c files and such. And yet I get told no such function in the system. So what could cause that. 

make clean
./configure
make
make install
No function.

**Comment by g33kcub** [comment]
PennMUSH version 1.8.6 patchlevel 0 -- That's what I'm running.

**Comment by ray73864** [comment]
I assume you followed the necessary steps in this? https://github.com/ray73864/aspace/wiki/local.dst-changes

Updating src/Makefile.in and src/local.dst need to be done before you run the penn configure script in order to make sure they get dealt with properly.

Check your src/local.c file and see if it has initSpace() in it, if it doesn't, then this is why you are not getting the sdb() function in-game.

**Comment by g33kcub** [comment]
I just copied the local.dst to local.c and configured then made and it's up and running now.

**Comment by g33kcub** [comment]
Do you happen to have a copy of the various materials you reference? As the web seems to have eaten them.

**Comment by ray73864** [comment]
It's strange, because configure copies src/Makefile.in to src/Makefile, and then when you run 'make', it is supposed to copy local.dst to local.c automatically, except when you already have a local.c file.

As for the various reference materials, all the ones I got were from aspace.whizy.com back in the day, the wayback machine may still have them available for download, I shall see if I can dig them up and put them on the net somewhere.

**Comment by DieterKoblenz** [comment]
There are references (like an outdated function info and attribs list) here:
ftp://sourcery.dyndns.org/archive/servers/tiny/mush/aspace
